# Generated by Django 4.0.4 on 2022-05-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_article_description_alter_article_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
    ]
